package:
  name: demo
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}.{{ environ['GIT_DESCRIBE_HASH'] }}

build:
  number: 0

source:
  git_url: https://github.com/dhirschfeld/demo.git

requirements:
  build:
  - python
  - setuptools

  run:
  - python
  - setuptools

about:
  license: BSD